language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rachitachittal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rachitachittal/react-test npm test

after_success:
  - docker build -t rachitachittal/multi-client ./client
  - docker build -t rachitachittal/multi-nginx ./nginx
  - docker build -t rachitachittal/multi-server ./server
  - docker build -t rachitachittal/multi-worker ./worker

#Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take those images and push them to dockerhub
  - docker push rachitachittal/multi-client
  - docker push rachitachittal/multi-nginx
  - docker push rachitachittal/multi-server
  - docker push rachitachittal/multi-worker


